apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ri5cd2le3-nodejs 
  janus-idp.io/tekton: ri5cd2le3-nodejs
  backstage.io/kubernetes-id: ri5cd2le3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ri5cd2le3-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml